stages:
  data_ingestion:
    cmd: python src/EVE_AI/pipeline/stage_01_data_ingestion.py
    deps:
      - src/EVE_AI/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion



  prepare_base_model:
    cmd: python src/EVE_AI/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/EVE_AI/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - LEARNING_RATE
      - DEPTH
      - ITERATIONS
    outs:
      - artifacts/prepare_base_model
      - artifacts/prepare_base_tokenizer



  training:
    cmd: python src/EVE_AI/pipeline/stage_03_training.py
    deps:
      - src/EVE_AI/pipeline/stage_03_training.py
      - config/config.yaml
      - artifacts/data_ingestion
      - artifacts/prepare_base_model
      - artifacts/prepare_base_tokenizer
    params:
      - VERBOSE
    outs:
      - artifacts/prepare_fitted_tokenizer
      - artifacts/training



  evaluation:
    cmd: python src/EVE_AI/pipeline/stage_04_evaluation.py
    deps:
      - src/EVE_AI/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion
      - artifacts/prepare_fitted_tokenizer
      - artifacts/training
    metrics:
    - scores.json:
        cache: false