artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?id=16c_EfTD4tK1uACPbVsVT9yo5bsEtHYgq
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion




prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pkl




prepare_base_tokenizer:
  root_dir: artifacts/prepare_base_tokenizer
  base_tokenizer_path: artifacts/prepare_base_tokenizer/prepare_base_tokenizer.pkl




prepare_fitted_tokenizer:
  root_dir: artifacts/prepare_fitted_tokenizer
  fitted_tokenizer_path: artifacts/prepare_fitted_tokenizer/prepare_fitted_tokenizer.pkl




preprocessor:
  root_dir: artifacts/prepare_preprocessor
  preprocessor_path: artifacts/prepare_preprocessor/prepare_preprocessor.pkl




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pkl